### PR TITLE
Create and publish sources jar

### PR DESCRIPTION
**Pull request by eddgrant**
Whilst IntelliJ's decompiled bytecode is pretty good, having the sources jar available would make it  easier to delve in to the code when trying to figure out which part of the library I should be using in my job scripts.

### CODE REVIEW

**Comment by eddgrant** [comment]
Apologies, had to fetch upstream to fix merge conflict.

**Comment by agilestevesmith** [comment]
Thanks, we'll look at this soon

**Comment by deepakhalale** [comment]
Hey @agilestevesmith. Do we know when we can get this PR merged as I think it would be really useful while debugging and IntelliJ's decompiler isn't playing well when decompiling Groovy bytecode.

**Comment by agilestevesmith** [comment]
@deepakhalale Please resolve conflicts and we will review when we have the time, we are flat out elsewhere in GitHub right now and also I'm unsure of our policy on source JARs and need to find the right person to ask

**Comment by agilestevesmith** [comment]
Closing, no activity for ~9 months

**Pull request closed without merging**
