### PR TITLE
Refactoring of deprecated options to be compatible with job-dsl 1.64

### PR DESCRIPTION
**Pull request by bbc-daniel**
Followed https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration

### CODE REVIEW

**Comment by bbc-daniel** [comment]
Hey @eddgrant fancy reviewing my PR 😃
We're like the Hotel California.

**Comment by eddgrant** [comment]
Hey @bbc-daniel !

Apolgies for the hugely delayed response, no idea why but I've not seen this PR until now :-(

We're in a bit of a pickle with this repository at the moment, unfortunately due to some internal stuff, we're not in a position to be able to upgrade it to be compatible with the latest DSL version. I can see that you've created a BBC fork, does this serve your needs for now?

We are aiming to address our blocking issues in the new year so will get things updated to the latest at that point. Apologies for the inconvenience!

Cheers,

Edd

**Comment by bbc-daniel** [comment]
Hey. No worries. Assumed you were busy closing loopholes or whatever you do at HMRC. Let us know if you move it on. We're good for just now. Jenkins is such a tangled web of dependencies I'm happy to leave it be.

**Comment by eddgrant** [comment]
Hey @bbc-daniel ,

We have (finally) got around to updating to v1.69 of the DSL, have released this as v11.1.0.

Just giving you a shout in case it's still of use to you guys.

Cheers!

**Pull request closed without merging**
